# Generated by Django 6.0.2 on 2026-03-28 17:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mae', models.FloatField()),
                ('rmse', models.FloatField()),
                ('r2', models.FloatField()),
                ('smape', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('SYSTEM_OVERVIEW', 'System Overview'), ('STORE_PERFORMANCE', 'Store Performance'), ('FORECAST_ACCURACY', 'Forecast Accuracy'), ('INVENTORY_OPT', 'Inventory Optimization'), ('ALERT_SUMMARY', 'Alert Summary')], max_length=40)),
                ('title', models.CharField(max_length=180)),
                ('schedule', models.CharField(default='MANUAL', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('LOGIN', 'Login'), ('UPLOAD', 'Upload'), ('FORECAST', 'Forecast'), ('REPORT', 'Report'), ('SETTINGS_UPDATE', 'Settings Update'), ('PROFILE_UPDATE', 'Profile Update'), ('PASSWORD_CHANGE', 'Password Change')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('status', models.CharField(default='DONE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ownerpanel.reportjob')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ownerpanel.store')),
            ],
        ),
        migrations.AddField(
            model_name='reportjob',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ownerpanel.store'),
        ),
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Store Owner'), ('ADMIN', 'Admin')], default='OWNER', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ownerpanel.store')),
            ],
        ),
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_type', models.CharField(choices=[('SALES', 'Sales Data'), ('INVENTORY', 'Inventory Data')], max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('rows_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='SUCCESS', max_length=30)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ownerpanel.store')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('role', models.CharField(choices=[('OWNER', 'Store Owner'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin')], default='OWNER', max_length=20)),
                ('timezone', models.CharField(choices=[('Asia/Kolkata', 'Asia/Kolkata'), ('UTC', 'UTC'), ('America/New_York', 'America/New_York'), ('Europe/London', 'Europe/London')], default='Asia/Kolkata', max_length=64)),
                ('email_notifications', models.BooleanField(default=True)),
                ('low_stock_alerts', models.BooleanField(default=True)),
                ('overstock_alerts', models.BooleanField(default=True)),
                ('forecast_alerts', models.BooleanField(default=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ownerpanel.store')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product_sku', models.CharField(max_length=60)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ownerpanel.store')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('store', 'date', 'product_sku'), name='uniq_sales_store_date_sku')],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(max_length=60)),
                ('product_name', models.CharField(max_length=140)),
                ('current_stock', models.IntegerField(default=0)),
                ('reorder_point', models.IntegerField(default=0)),
                ('safety_stock', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('OK', 'Healthy'), ('LOW', 'Low Stock'), ('CRIT', 'Critical'), ('OVER', 'Overstock')], default='OK', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ownerpanel.store')),
            ],
            options={
                'unique_together': {('store', 'product_sku')},
            },
        ),
        migrations.CreateModel(
            name='ForecastRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product_sku', models.CharField(max_length=60)),
                ('predicted_qty', models.FloatField()),
                ('confidence', models.FloatField(default=0.75)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ownerpanel.store')),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'date'], name='ownerpanel__store_i_a5d342_idx'), models.Index(fields=['store', 'product_sku'], name='ownerpanel__store_i_12edb0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('CRITICAL_LOW', 'Critical Low Stock'), ('OVERSTOCK', 'Overstock')], max_length=30)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Warning'), ('CRIT', 'Critical')], default='INFO', max_length=10)),
                ('product_sku', models.CharField(max_length=60)),
                ('product_name', models.CharField(blank=True, max_length=150, null=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, null=True)),
                ('current_stock', models.FloatField(default=0)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='ownerpanel.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'alert_type'], name='ownerpanel__store_i_16128a_idx'), models.Index(fields=['store', 'is_resolved'], name='ownerpanel__store_i_ae56c0_idx'), models.Index(fields=['store', 'product_sku'], name='ownerpanel__store_i_fd0da2_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_resolved', False)), fields=('store', 'product_sku', 'alert_type'), name='unique_active_alert_per_product')],
            },
        ),
    ]
