# Generated by Django 6.0.2 on 2026-04-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownerpanel', '0002_forecastrecord_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastrecord',
            name='created_at',
        ),
    ]
