# Generated by Django 6.0.2 on 2026-04-01 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownerpanel', '0004_forecastbatch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForecastBatch',
        ),
    ]
