# Generated by Django 6.0.2 on 2026-04-01 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerpanel', '0005_delete_forecastbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ownerpanel.store')),
            ],
        ),
    ]
